// Generated by CoffeeScript 1.8.0
var english, kanadict, katakana, nextword, randomwords, starttime, submit, togo, togo_text;

english = $('#english');

katakana = $('#katakana');

togo_text = $('#togo');

togo = 50;

starttime = 0;

kanadict = {};

randomwords = [];

$.getJSON('kanadict.json', function(response) {
  var i, j, _i, _ref, _ref1, _results;
  kanadict = response;
  randomwords = Object.keys(kanadict);
  _results = [];
  for (i = _i = _ref = randomwords.length - 1; _ref <= 1 ? _i <= 1 : _i >= 1; i = _ref <= 1 ? ++_i : --_i) {
    j = Math.floor(Math.random() * (i + 1));
    _results.push((_ref1 = [randomwords[j], randomwords[i]], randomwords[i] = _ref1[0], randomwords[j] = _ref1[1], _ref1));
  }
  return _results;
});

nextword = function() {
  togo_text.text("" + togo + " to go");
  english.val('');
  english.focus();
  katakana.unbind('mouseenter mouseleave');
  return katakana.text(randomwords.pop());
};

submit = function() {
  var time_ellapsed, _ref;
  switch (english.val().toLowerCase().replace(' ', '')) {
    case 'start':
      _ref = [50, new Date().getTime()], togo = _ref[0], starttime = _ref[1];
      break;
    case kanadict[katakana.text()]:
      togo = togo - 1;
      break;
    default:
      togo = togo + 2;
  }
  if (togo === 0) {
    time_ellapsed = Math.round((new Date().getTime() - starttime) / 1000);
    togo_text.text("Done in " + time_ellapsed + " seconds!");
  } else {
    nextword();
  }
};
